#!/bin/bash
# Handy script for cloning repositories
cd AlienCivilisations/lib
mkdir derelict
cd derelict
git clone https://github.com/DerelictOrg/DerelictUtil.git
git clone https://github.com/DerelictOrg/DerelictGL3.git
git clone https://github.com/DerelictOrg/DerelictFT.git
git clone https://github.com/DerelictOrg/DerelictSDL2.git
git clone https://github.com/DerelictOrg/DerelictGLFW3.git
